name: Build, Test and Package teleinfo2mqtt
on:
  push:
  workflow_dispatch:
env:
  NODE_VERSION: '18'
  IMAGE_VERSION: develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: node install
      run: |
        sudo apt update
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
        nvm install $NODE_VERSION
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: export IMAGE_VERSION=${TRAVIS_BRANCH//\//\_}
    - run: export IMAGE_VERSION=${IMAGE_VERSION//\#/\_}
    - run: docker run --rm --privileged multiarch/qemu-user-static --credential yes --persistent yes
    - run: "(cd app && npm ci)"
    - run: "(cd app && npm run lint)"
    - run: "(cd app && npm test)"
    - run: if [ "${ github.ref_name }" == "master" ] ; then export IMAGE_VERSION=latest; fi
      if: "${{ success() }}"
    - run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      if: "${{ success() }}"
    - run: docker version
      if: "${{ success() }}"
    - run: make prepare
      if: "${{ success() }}"
    - run: make build IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/teleinfo2mqtt IMAGE_VERSION=$IMAGE_VERSION PLATFORMS=linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
      if: "${{ success() }}"
