name: Build, Test and Package teleinfo2mqtt
on:
  push:
  workflow_dispatch:
env:
  NODE_VERSION: '18'
  CC_TEST_REPORTER_ID: 5167fc209c026a59fa2f9e21c7e21efa2ce09989a62ca8bc775f2240d8b9f662
  IMAGE_VERSION: develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: nvm install
      run: |
        sudo apt update
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        source ~/.bashrc
        nvm install $NODE_VERSION
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: export IMAGE_VERSION=${TRAVIS_BRANCH//\//\_}
    - run: export IMAGE_VERSION=${IMAGE_VERSION//\#/\_}
    - run: docker run --rm --privileged multiarch/qemu-user-static --credential yes --persistent yes
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./app/cc-test-reporter
    - run: "(cd app && chmod +x ./cc-test-reporter)"
    - run: "(cd app && ./cc-test-reporter before-build)"
    - run: "(cd app && npm ci)"
    - run: "(cd app && npm run lint)"
    - run: "(cd app && npm test)"
    - run: "(cd app && ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT)"
      if: "${{ success() }}"
    - run: if [ "${{ github.ref }}" == "master" ] ; then export IMAGE_VERSION=latest; fi
      if: "${{ success() }}"
    - run: if [ ! -z "${{ github.ref }}" ] ; then export IMAGE_VERSION=${{ github.ref }}; fi
      if: "${{ success() }}"
    - run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
      if: "${{ success() }}"
    - run: docker version
      if: "${{ success() }}"
    - run: make prepare
      if: "${{ success() }}"
    - run: make build IMAGE_NAME=$DOCKERHUB_USERNAME/teleinfo2mqtt IMAGE_VERSION=$IMAGE_VERSION PLATFORMS=linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
      if: "${{ success() }}"
